// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tasker.DataAccessLayer;

namespace Tasker.DataAccessLayer.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20191014111831_changeidtoguid")]
    partial class changeidtoguid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Tasker.Model.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Deadline");

                    b.Property<string>("Description");

                    b.Property<int>("Priority");

                    b.Property<int>("State");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Deadline = new DateTime(2019, 10, 14, 13, 18, 31, 272, DateTimeKind.Local).AddTicks(1889),
                            Description = "Test description",
                            Priority = 1,
                            State = 1,
                            Title = "Test title"
                        },
                        new
                        {
                            Id = -2,
                            Deadline = new DateTime(2019, 10, 14, 13, 18, 31, 274, DateTimeKind.Local).AddTicks(7079),
                            Description = "Lorem ipsum",
                            Priority = 2,
                            State = 1,
                            Title = "Test blabla"
                        },
                        new
                        {
                            Id = -3,
                            Deadline = new DateTime(2019, 10, 14, 13, 18, 31, 274, DateTimeKind.Local).AddTicks(7118),
                            Description = "Sit dolor am alet nem tudom hogy van",
                            Priority = 3,
                            State = 1,
                            Title = "Test 123"
                        },
                        new
                        {
                            Id = -4,
                            Deadline = new DateTime(2019, 10, 14, 13, 18, 31, 274, DateTimeKind.Local).AddTicks(7122),
                            Description = "Test description",
                            Priority = 4,
                            State = 1,
                            Title = "Test aefawf"
                        },
                        new
                        {
                            Id = -5,
                            Deadline = new DateTime(2019, 10, 14, 13, 18, 31, 274, DateTimeKind.Local).AddTicks(7125),
                            Description = "Test description",
                            Priority = 5,
                            State = 1,
                            Title = "Test w1rawer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
